name: golf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - torchvision
  - pytorch-cuda=11.8
  - matplotlib=3.7.0  # Changed to match SAM2's requirement
  - pandas=2.2.3
  - ultralytics=8.3.128
  - opencv
  - scipy
  - tqdm
  - numpy>=1.24.4  # Updated to match SAM2's minimum
  - pillow>=9.4.0  # Updated to match SAM2's minimum
  - hydra-core>=1.3.2
  - iopath>=0.1.10
  - loguru
  - lmdb
  - pip
  - pip:
    - tikzplotlib
    - jpeg4py
    - eva-decord
